DOC: scan area detector with motor(s)
BCDA-APS/bluesky_training pull request #311
Opened 2024-06-14 18:03 UTC by prjemian

- close #308 

@sureshnaps, @qzhang - Can you examine this notebook?  It can guide you during commissioning activities.

2024-06-14 20:58 UTC, rodolakis commented
In general, I find some of the markdown comment difficult to find in the middle of the code cell output, like here for example:

<img width="1017" alt="image" src="https://github.com/BCDA-APS/bluesky_training/assets/39918069/5822edc2-6cbb-451c-8527-ea860b42ad5a">


maybe adding bullet point or a `<br>` before the comment would help.

2024-06-14 21:00 UTC, rodolakis commented
Not sure what that bug was in the last few suggestions. It was displaying the correct sentence before pressing the green button, but then showed the code for an image as the original...

2024-06-14 21:01 UTC, rodolakis requested changes
Minor formatting and rephrasing.

2024-06-14 23:13 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +    "- Record the unique ID of the image."
Not the right word here.  "Configure the detector **_for_** Collect $n$ image frame(s) ..."

2024-06-14 23:15 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +    "run with the area detector object `simdet`."
Such as:

> Show the data from area detector `simdet`.  This is the data collected by the `RE` during a run.

2024-06-14 23:16 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +    "## Diagnostics (optional)\n",
I'll take this point and see how to apply generally.

2024-06-14 23:17 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
I don't understand this review comment.

2024-06-14 23:18 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
I don't understand this review comment.

2024-06-14 23:18 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
I don't understand this review comment.

2024-06-14 23:18 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
I don't understand this review comment.

2024-06-14 23:18 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
I don't understand this review comment.

2024-06-14 23:53 UTC, prjemian commented
@rodolakis I believe this is ready for review again.

2024-06-15 06:23 UTC, prjemian commented on docs/source/howto/_ad_v_motors.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkUAAAHFCAYAAAD8Jo2EAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8fJSN1AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
> Not sure what that bug was in the last few suggestions. It was displaying the correct sentence before pressing the green button, but then showed the code for an image as the original...

Probably these next comments.

2024-06-15 15:08 UTC, rodolakis commented
OK so this is what I was trying to suggest:

<img width="873" alt="image" src="https://github.com/BCDA-APS/bluesky_training/assets/39918069/1caf0804-4ed0-47c1-a516-30a0e9a2a8ef">

2024-06-15 15:14 UTC, rodolakis commented
<img width="1060" alt="image" src="https://github.com/BCDA-APS/bluesky_training/assets/39918069/8dd21874-a35a-4de0-92a8-c459cae1fe92">


I would write instead:

    "Both motors, `m1` and `m2`, move at the same time. Below is a plot showing the readback values of each motor during a two-motor `scan` versus the data point number:\n",

2024-06-15 15:20 UTC, rodolakis commented
> The file name, as the catalog will find its image contents, is reconstructed:

I am not sure I understand this sentence. I was proposing:

"The catalog uses the file name to locate and retrieve its image contents. This file name is reconstructed as follows:"

2024-06-15 15:22 UTC, rodolakis commented
> "The second motor of the `grid_scan` (`m2`) is snaked.  It's direction changes with each subsequent increment of the
> first motor (`m1`).  Here's a plot of readback value of each motor from a `grid_scan` plotted *v*. data point number:\n",

I was proposing:

    "During the `grid_scan`, the second motor (`m2`) moves in a snaking pattern: its direction changes with each subsequent increment of the first motor (`m1`). Below is a plot showing the readback values of each motor during a `grid_scan` versus the data point number:\n",

2024-06-15 15:24 UTC, rodolakis commented
<img width="905" alt="image" src="https://github.com/BCDA-APS/bluesky_training/assets/39918069/6bcfc64a-4215-4ffd-84e9-0db61bead758">



- I was proposing instead:


    All along, quietly in the background, the data has been saved both to a catalog
    and to a SPEC data file. The total counts, max counts, and unique ID from all
    scans can be plotted from the SPEC file using PyMCA or NeXpy. The image content
    is not stored in the SPEC file, so images cannot be viewed from it. However,
    references to the images are save as comments.  See the comment lines that
    match a search for `resource {'spec': 'AD_HDF5'}`, such as this one:

2024-06-15 15:29 UTC, rodolakis commented
@prjemian  I rewrote my broken comments. I still cannot quote anything as a github "suggestions".

2024-06-15 18:22 UTC, prjemian commented
@rodolakis : I believe I have responded to all your comments.  Thanks for the thorough review.

2024-06-19 22:55 UTC, rodolakis commented
All good. Everything has been resolved as far as I am concerned except for one minor formatting suggestion (I tagged you on it).
So minor that I'm fine with merging with or without.

2024-06-19 22:55 UTC, rodolakis approved these changes

2024-06-19 22:55 UTC, rodolakis commented on docs/source/howto/_ad_v_motors.ipynb
> +    "Show the data from area detector `simdet`.\n",
@prjemian  this is the only comment left that has not been resolved. Minor though, but would be nice to add it.

2024-06-20 00:17 UTC, prjemian commented
@rodolakis Thanks!

2024-06-20 00:17 UTC, merged